### PR TITLE
Added more flexibility to the eigs function

### PR DESCRIPTION
**Pull request by roxyboy**
Allows the instability function to have more options for the sparse.eigs function

### CODE REVIEW

**Comment by rabernat** [comment]
Looks like you have to update the tests as well in order to match the new syntax.

**Comment by rabernat** [comment]
Cool, nice work! I see you added the viscosity too.

**Comment by roxyboy** [comment]
It seems that exponential profiles give credible results, even without the lateral viscosity, i.e. Ah=0... The profiles (black line: actual profile, red line: exponential fit) I used and the results were:

Profiles:
screen shot 2016-05-29 at 12 04 48

Results:
screen shot 2016-05-29 at 12 05 00

**Comment by roxyboy** [comment]
Adding lateral viscosity (Ah=10) gave:

screen shot 2016-05-29 at 12 18 17

**Pull request merged**
